# ===========================================================================
# make_table_network_changes.R
#
# PURPOSE: Paper Table 1 — national totals of rail and road infrastructure
#          at each observed period, and their changes. LaTeX output ready
#          for \input{} from the paper.
#
# READS:
#   data/derived/base/networks/rails_by_district.parquet
#   data/derived/base/networks/roads_by_district.parquet
#
# PRODUCES:
#   results/tables/table_1_network_changes.tex
#   results/tables/table_1_network_changes.csv   (convenience copy)
#
# CONTENT:
#   - Rail: km in 1960, km in 1986, absolute change, percent change.
#     Optionally: closed-during-dictatorship vs closed pre-dictatorship
#     breakdown.
#   - Roads (paved+gravel): km in 1954, 1970, 1986, absolute and
#     percent changes.
# ===========================================================================

main <- function() {
    source(file.path(here::here(), "code", "config.R"), echo = FALSE)
    source(file.path(dir_code, "base", "utils.R"), echo = FALSE)

    if (!dir.exists(dir_tables)) dir.create(dir_tables, recursive = TRUE)

    rails <- arrow::read_parquet(
        file.path(dir_derived_networks, "rails_by_district.parquet")
    )
    roads <- arrow::read_parquet(
        file.path(dir_derived_networks, "roads_by_district.parquet")
    )

    rows <- build_rows(rails, roads)
    write_latex(rows, file.path(dir_tables, "table_1_network_changes.tex"))
    write_csv(rows,   file.path(dir_tables, "table_1_network_changes.csv"))

    cat(format_for_console(rows), sep = "\n")
}

# ---------------------------------------------------------------------------
# Build data rows
# ---------------------------------------------------------------------------
build_rows <- function(rails, roads) {
    rail_1960 <- sum(rails$tot_rails_1960, na.rm = TRUE)
    rail_1986 <- sum(rails$tot_rails_1986, na.rm = TRUE)
    rail_closed_dict    <- sum(rails$status1979_2, na.rm = TRUE)
    rail_closed_predict <- sum(rails$status1979_3, na.rm = TRUE)

    road_1954 <- sum(roads$pav_and_grav_1954, na.rm = TRUE)
    road_1970 <- sum(roads$pav_and_grav_1970, na.rm = TRUE)
    road_1986 <- sum(roads$pav_and_grav_1986, na.rm = TRUE)

    list(
        rail_1960           = rail_1960,
        rail_1986           = rail_1986,
        rail_change         = rail_1986 - rail_1960,
        rail_pct_change     = 100 * (rail_1986 - rail_1960) / rail_1960,
        rail_closed_dict    = rail_closed_dict,
        rail_closed_predict = rail_closed_predict,
        road_1954           = road_1954,
        road_1970           = road_1970,
        road_1986           = road_1986,
        road_change_86_54   = road_1986 - road_1954,
        road_pct_change_86_54 = 100 * (road_1986 - road_1954) / road_1954
    )
}

# ---------------------------------------------------------------------------
# LaTeX output (booktabs, threeparttable-friendly)
# ---------------------------------------------------------------------------
write_latex <- function(r, path) {
    # Helper: format km with thousands-separator comma
    km <- function(x) format(round(x), big.mark = ",")
    pct <- function(x) sprintf("%+.1f", x)

    lines <- c(
        "% table_1_network_changes.tex",
        "% Auto-generated by make_table_network_changes.R. Do not edit.",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        " & 1960 & 1986 \\\\",
        "\\midrule",
        "\\multicolumn{3}{l}{\\textit{Panel A. Railways}} \\\\",
        sprintf("Total km & %s & %s \\\\", km(r$rail_1960), km(r$rail_1986)),
        sprintf(
            "Net change & & %s (%s\\%%) \\\\",
            km(r$rail_change), pct(r$rail_pct_change)
        ),
        sprintf(
            "\\quad closed during dictatorship 1976--83 & & %s \\\\",
            km(r$rail_closed_dict)
        ),
        sprintf(
            "\\quad closed 1960--66, pre-dictatorship & & %s \\\\",
            km(r$rail_closed_predict)
        ),
        "\\addlinespace",
        "\\multicolumn{3}{l}{\\textit{Panel B. Paved+gravel roads}} \\\\",
        " & 1954 & 1986 \\\\",
        sprintf("Total km & %s & %s \\\\", km(r$road_1954), km(r$road_1986)),
        sprintf(
            "Net change & & %s (%s\\%%) \\\\",
            km(r$road_change_86_54), pct(r$road_pct_change_86_54)
        ),
        sprintf("\\quad 1970 total & \\multicolumn{2}{c}{%s} \\\\",
                km(r$road_1970)),
        "\\bottomrule",
        "\\end{tabular}"
    )
    writeLines(lines, path)
    message("Saved: ", path)
}

# ---------------------------------------------------------------------------
# CSV copy (convenient for inspection)
# ---------------------------------------------------------------------------
write_csv <- function(r, path) {
    df <- data.frame(
        variable = names(r),
        value    = round(unlist(r, use.names = FALSE), 2)
    )
    write.csv(df, path, row.names = FALSE)
    message("Saved: ", path)
}

# ---------------------------------------------------------------------------
# Plain-text console preview
# ---------------------------------------------------------------------------
format_for_console <- function(r) {
    c(
        "",
        strrep("-", 60),
        "Table 1 — Network changes",
        strrep("-", 60),
        "Panel A. Railways",
        sprintf("  1960                                    %10.0f km",
                r$rail_1960),
        sprintf("  1986                                    %10.0f km",
                r$rail_1986),
        sprintf("  Net change                              %10.0f km (%.1f%%)",
                r$rail_change, r$rail_pct_change),
        sprintf("    closed during dictatorship (76-83)    %10.0f km",
                r$rail_closed_dict),
        sprintf("    closed 1960-66, pre-dictatorship      %10.0f km",
                r$rail_closed_predict),
        "",
        "Panel B. Paved + gravel roads",
        sprintf("  1954                                    %10.0f km",
                r$road_1954),
        sprintf("  1970                                    %10.0f km",
                r$road_1970),
        sprintf("  1986                                    %10.0f km",
                r$road_1986),
        sprintf("  Net change 1954 -> 1986                 %10.0f km (%+.1f%%)",
                r$road_change_86_54, r$road_pct_change_86_54),
        strrep("-", 60)
    )
}

main()
